### ISSUE TITLE
Backer: Magic link sign in w. upgrade path to GitHub

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1052]
**Problem**
Upon funding an issue today, backers provide their email and can only upgrade to an account if they do so directly after the pledge on the "Thank you"-page via GitHub login. We should improve this to support backers to login with an account associated with their email using magic links. From there they can easily upgrade their account with GitHub in their settings and that we encourage them to do so via the dashboard.

Full design of the flow is in [Figma](https://www.figma.com/file/1p2oOjsRBgSrr3SC4zySJG/Polar-Latest-Design?type=design&node-id=222%3A6136&mode=design&t=2dP5iMGSceiaWzBp-1). Core flow illustrated below. 

![Image](https://github.com/polarsource/polar/assets/281715/f40eb29c-b827-4fdc-b455-860fc713cf46)
![Image](https://github.com/polarsource/polar/assets/281715/eda7d67b-67fd-40cb-bd0e-ef8e3308866e)
![Image](https://github.com/polarsource/polar/assets/281715/294a87a9-5006-418b-8ccf-8988e6638f89)
![Image](https://github.com/polarsource/polar/assets/281715/ea724d57-596c-47c5-8ec3-74206118085a)

**Considerations**
- We need to create users for each successful pledge. Basic user without GitHub connection.
- We need a migration script to generate such users for historical, successful, pledges (no abandoned checkouts)
- We need to make sure pledges for the same email are connected to a single user

**Todo**
_Not final. To be flushed out as we build _
- [x] Get || Create a user once a pledge is made tied to the given email (case sensitive/insensitive?)
- [x] Connect the pledge to the user
- [x] Ability to sign in using magic links and a verification code we send in the email too for additional security (Vercel-style)
   - [x] Link should expire within X minutes (30?)
   - [x] Link should only be able to be used once
- [x] Ability to connect GitHub to the account via settings
- [x] Automatically connect accounts if backer has an email account and later signs in with GitHub which has the same email address

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1052">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1052/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1052/pledge.svg">
</picture>
</a>

**Comment by birkjernstrom** [comment]
Of course, thanks @frankie567 🙂

Re: best practice of case sensitive/insensitive logic. Sounds completely reasonable to avoid fake accounts to be registered to create duplicates for malicious intents and that we send to the exact email address provided for the same reason.

Re: Flow. Completely agree with you regarding too much complexity and clicks with Vercel. So I removed the additional verification steps after clicking the email link. The verification code was not something I imagined would require input, i.e similar to 2FA, but included in the email for the security concerned to be able to verify (avoid phishing). Potentially gives additional comfort. But I agree that I've only seen Vercel do that so perhaps it's overkill. However, it might also help with avoiding email bundling (Gmail) due to more different content (not sure links are respected in the same way). So that could be part of the reason. Otherwise, I'm fine to go without it too.

**Comment by frankie567** [comment]
Thanks!

Regarding this "visual" verification code, I really think it doesn't bring much value. Worse, I find it to be quite confusing (some people will probably wonder where they need to input it).

**Comment by birkjernstrom** [comment]
That's a fair point. Let's go without it 👍🏼

**Comment by frankie567** [comment]
I would like a clarification on a specific use-case.

So, if a user makes a pledge, we automatically create them an account; and they can login with their email afterwards. That's OK.

However, what happens if the user is completely new when reaching the **Sign in** page? Do we automatically create them an account?

**Comment by birkjernstrom** [comment]
Great clarifying question @frankie567 

Thought about it and I think we should automatically create an account in that scenario. However, I think this would require the following changes:
1. We add the legal disclaimer from signup to login too, e.g "By using Polar you agree to ...". So that we don't accidentally create a route without ToS approval for new accounts.
2. We should add copy in the form of "A magic link will be sent to your email to sign in. If no account exists, it will be created"


I prefer that over 2) showing an error requiring additional clicks for the user. Simultaneously, that pattern leaks account existence information. So the other 3) option of simply silently failing and letting the user figure it out that they need to signup and doing 2, is awful.

**Comment by birkjernstrom** [comment]
The second copy of "An email link..." should be the notice upon clicking sign in vs. upfront - that would be too much context/copy upfront.

**Comment by frankie567** [comment]
Ok, makes sense.

However, in the current state, I don't see where we have the "agree terms" copy? The login page just shows the GitHub button and we don't seem to have a dedicated signup page.

**Comment by birkjernstrom** [comment]
Sorry you're absolutely right. I forgot to add some context and simultaneously mixed up backer vs. maintainer flows to make things more confusing :)

Re: Sign up. We're introducing a more explicit sign up page, but for maintainers which we'll link to from our new, updated, website that I'll aim to launch early next week. Currently, it's hidden here https://polar.sh/signup/maintainer - we need to add the legal disclaimer to it though. I'll create a separate issue for that so we can address it before it goes live.

However, you're absolutely right that we don't have an explicit sign up for backers which this email flow is mainly targeting. I think we might introduce that in the future with a dedicated page for them, but for now, let's only use the login page with the additions above: Adding the legal disclaimer at the bottom (text-sm gray-400 perhaps) and message upon clicking enter of a magic link being sent and an account having been created if none existed. Does that make sense?

**Comment by frankie567** [comment]
It makes sense!

As a side-note, it seems that we have a feature that prompts the user to accept terms once logged in:

https://github.com/polarsource/polar/blob/ec823272b943496fccc757bdbc4081c733d7e764/clients/apps/web/src/components/Dashboard/Gatekeeper/Gatekeeper.tsx#L13-L14

So there is an "action-required" step anyway besides the simple copy on the login/sign up.

**Comment by birkjernstrom** [comment]
Yes we should remove this once we've added the note upfront during sign up/login. Nice to remove this additional step.

**Comment by frankie567** [comment]
I'm currently working on the ability to connect its GitHub account from user settings.

Currently, whenever we login, we *always* update the email with the one provided by GitHub. So if it changes on GitHub, it'll change on Polar on the next login.

Now that users can sign in/sign up with their email, it doesn't feel "right" to me to have this behavior anymore. It's even more true with this *link my GitHub* feature. Imagine the following scenario:

1. User makes a pledge anonymously and inputs their email `john@example.com`.
2. They now have a Polar account and can sign in with a magic link with this email.
3. Next, they go to their settings and connect their GitHub account. Their GitHub account is under the email `john@gmail.com`.
4. *Bip boup beep* (👈 this is the noise of the server working 😄) Their Polar account is now attached to the email `john@gmail.com`.

We silently change their email, which is probably not what they want/expect.

IMO, we should establish the following rule: we **should always keep the first email we get upon signup** (whether its from GitHub or email signup). No matter if it changes afterwards on GitHub.

In a follow-up improvement, we should give them the ability to change their email properly from Polar.

What do you think @birkjernstrom?

**Comment by frankie567** [comment]
Also looking at the user creation after successful pledge. Currently, the UI look like this:

<img width="1033" alt="Capture d’écran 2023-09-15 à 09 14 57" src="https://github.com/polarsource/polar/assets/1144727/5fad9f5b-394c-4bd6-aee5-94e97241a521">

Shall we remove the **Sign up with Polar** callout or keep it and incentive to "upgrade" to their GitHub account?

**Comment by birkjernstrom** [comment]
> IMO, we should establish the following rule: we **should always keep the first email we get upon signup** (whether its from GitHub or email signup). No matter if it changes afterwards on GitHub.
> 
> In a follow-up improvement, we should give them the ability to change their email properly from Polar.
> 
> What do you think @birkjernstrom?

I completely agree on both accounts. Let's retain the first email as their primary and add a backlog issue (enhancement) to allow changing the primary in the future.

While we're on the topic, I want to make sure we're aligned on the following scenarios.

**Authenticated email-only user** who connects their GitHub will have both email and GitHub tied to the same underlying user account. Both have been verified (magic link & GitHub's verification).

The opposite direction is a bit more tricky. 

**Authenticated GitHub user** who enters a different email when making a pledge. I assume the following?
- The pledge itself will be connected to their account
- Email will initially not be connected to their account until they've verified it, i.e magic link 
- Upon initial email verification any pledges tied to the identical email (non-authenticated prior) will be merged/tied to the verified account - now with both the email & GitHub account linked.

> 4. _Bip boup beep_ (👈 this is the noise of the server working 😄) [...]
Haha thanks for this gem.

**Comment by frankie567** [comment]
> **Authenticated email-only user** who connects their GitHub will have both email and GitHub tied to the same underlying user account. Both have been verified (magic link & GitHub's verification).

Yes!

> **Authenticated GitHub user** who enters a different email when making a pledge. I assume the following?
> 
> * The pledge itself will be connected to their account
> * Email will initially not be connected to their account until they've verified it, i.e magic link
> * Upon initial email verification any pledges tied to the identical email (non-authenticated prior) will be merged/tied to the verified account - now with both the email & GitHub account linked.

My call in this context would actually be simpler: if the user is already authenticated with GitHub, we already have an email address. The other email address he enters during pledging will be filed on Stripe, but on our side, we should do nothing with it (cf. the rule we agreed upon).

It's worth to note that, in the current state, a user who signs ups with GitHub can automatically logs in with a magic link, no action is required.

**Comment by frankie567** [comment]
@birkjernstrom Thank you for the design!

I understand that we want to keep the **Connect GitHub** button. However, in order to do that, we need first to verify the email of the user. So, their are several ways we could do this:

## Ideal flow

* Click on **Connect GitHub**
* Prompt to verify the email address (in a modal?)
    * For a better UX, we should send a verification code the user could copy/paste (this way, they don't have to switch window)
    * *This is a slightly different flow from the magic link one* 
* Once done, we can proceed with the GitHub connection.

## Less ideal flow

* Remove **Connect GitHub** button, only keep **Sign in with email**
* The user goes through the magic link flow
* The user is now logged, they can connect to GitHub from their settings

What do you think @birkjernstrom?

**Comment by birkjernstrom** [comment]
Right of course, I didn't fully think it through 😓 I thought about it over lunch now and this is what I propose.

I'll design a prompt to signup/signin with GitHub on the main pledge page. I think that's better since:
- Good to nudge upfront for social pledges (https://github.com/polarsource/polar/issues/1101)
- Will be required for certain funding types, e.g pay on completion (https://github.com/polarsource/polar/issues/1128)
- Will be beneficial down the road once we support pledging on behalf of teams/companies (based on GitHub memberships)

With that in-place, I think backers either connect GitHub upfront or they actively won't want to at this stage and therefore we wouldn't convert them regardless on the "Thank You"-page. So we can disregard GitHub upsell entirely on the "Thank you"-page; since email-only users are prompted to upgrade once logged in within the dashboard for an enhanced experience. This is the "Less ideal" flow you outlined. 

I'll update the "Thank you"-card accordingly now quickly and then look at the GitHub prompt on the pledge page.

**Comment by birkjernstrom** [comment]
Updated design & copy. Note that we should remove the "Continue with GitHub" entirely in the topbar (same issue there as the one uncovered here with the initial design). I think we can change it to be a simple "Login"-button instead that redirects to `/login`. Can you make that change too @frankie567 as part of this so we have it fully resolved?

<img width="958" alt="Screenshot 2023-09-18 at 13 53 09" src="https://github.com/polarsource/polar/assets/281715/3f0da355-26cb-4abc-b56b-e3baf47ed440">

[Figma Link](https://www.figma.com/file/1p2oOjsRBgSrr3SC4zySJG/Polar-Latest-Design?type=design&node-id=222%3A6136&mode=design&t=DhprbGFDaEgjrCx5-1)

**Comment by frankie567** [comment]
Sure! Thank you, Birk!

**Comment by birkjernstrom** [comment]
No need to thank me. I live in Figma these days and aim to serve :)

**Comment by frankie567** [comment]
Happy to *finally* close this!

* The new *Thank you* page is live.
* Dangling pledges have been linked to a user account
