### ISSUE TITLE
Add issues v2 with search & suggestions

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1100]
**Dependencies:** N.A

### What
Ability to search repositories and issues with suggested results (issues) on GitHub via the "Add issues" module on Polar.new & backer dashboard. We should use the same module across both.

### Why
- Current flow requires backer to switch from Polar to GitHub to get a specific issue link/reference
- ...It's also boring then as a result :-)
- Better search/autocomplete creates a more effective, fun and polished experience

### How

Should use the cmd+k style of searching and applying filters.
- Single word? Search organizations & repositories.
	- Suggest 5 results during typing (with reasonable delay)
	- Arrow keys to navigate. Enter adds the org/repository as a filter.
	- Shows the top issues.
	- Typing searches amongst the issues.
- Multiple words? Search issues directly vs. orgs/repos.

**Design**
TODO

**Todo**
- [ ] Build the updated "Add issue" module
- [ ] Implement on Polar.new
- [ ] Implement in backer /feed

### Decision log

**Rate limiting & unauthenticated usage**
Unless the backer is signed in to Polar, we'll have to use our Polar user and its rate limit. Automatic suggestions upon typing will significantly increase our rate limit consumption.

	Decision: Design will include a signup upsell on Polar.new (where the issue would be) regardless of this. However, we can then in case of such an API error on our end prompt the user to either 1) signup or 2) provide a full URL/reference (as today).

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1100">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1100/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1100/pledge.svg">
</picture>
</a>

**Comment by birkjerntest** [comment]
Testing something here
