### ISSUE TITLE
Social funding

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1101]
**Dependencies:** N.A

### What
Show backers behind pledges to maintainers (dashboard) and the public via the badge and pledge page.

### Why
- Requested by maintainers
- Reward to backers
- Social proof for other potential backers
- More of a fun product experience :-)

### How

**Design**
TODO

**Todo**
- [ ] ~~Implement `is_anonymous` boolean flag on `pledges` – default `false`.~~
- [ ] ~~Set `is_anonymous` to `true` in migration script when adding the column to respect historical state of pledges~~
- [ ] ~~Implement "Pledge anonymously" checkbox on pledge badge – default off~~
- [x] Show backers in connection with the pledges on the maintainers dashboard
- [x] Show backers in the pledge embed badge
- [x] Show backers on the pledge page

### Decision log
**Email-only pledges**
We support "guest checkout", i.e email-only with an upsell to connect GitHub post checkout. We always want to support this flow and therefore can't count on GitHub profiles, i.e avatars.

	Decision #1: Show anonymous avatar instead of profile picture.
	Decision #2: Show email address instead of GitHub username.

**Historical pledges**
Up until this is shipped, all pledges have effectively been anonymous – not shown anywhere. How do we treat them? Do we support anonymous in the future?

	Decision #1: Implement support for anonymous pledges (on/off – default off except for historicals). We want to optimize for conversion rate and anonymous pledges are not too uncommon elsewhere.
	Decision #2: Treat all historical pledges as anonymous given support for the above.
	

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1101">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1101/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1101/pledge.svg">
</picture>
</a>

<sub>[POL-63](https://linear.app/polar-sh/issue/POL-63)</sub>

**Comment by zegl** [comment]
> Up until this is shipped, all pledges have effectively been anonymous – not shown anywhere. How do we treat them? Do we support anonymous in the future?

Clarification: Pledgers are _anonymous_ in regards to the public internet, but the receiver of the pledge can see who pledged on the /finance page.

**Comment by zegl** [comment]
Removing this from myself as it's blocked by https://github.com/polarsource/polar/labels/design%20needed
