### ISSUE TITLE
🎯 Fund on completion

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1104]
### What
Ability for backers to select a funding amount to pay once the issue is completed vs. upfront. 

### Why?
- Let's get maintainers as much funding as possible
- Backers have requested the desire to pledge, but pay once the issue is completed vs. upfront.
- Higher conversion rate

### How

- [x] Show the option to pay on completion in the pledge page. Calling out that it's a weaker signal vs. upfront.
- [x] Show such pledges differently in the dashboard to make it clear to the maintainer
- [x] Send payment request upon completion to backers. Requiring them to pay within the same dispute window we have today for upfront payments.

**Design**
TODO

### Dependencies
#1101 Social funding. We should require such pledges to be from authenticated GitHub accounts. So we can showcase profiles to the maintainer and create social proof/trust. Otherwise, it's likely to be abused by anonymous emails.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1104">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1104/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1104/pledge.svg">
</picture>
</a>

**Comment by zegl** [comment]
Really hot! 🔥  I'll start by working on getting the new funding methods design out, and then continue with the new left side of this page.
