### ISSUE TITLE
🎯💝 Rewards

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1125]
### What
Support setting & promoting contribution rewards upfront, i.e more like bounties.

### Why?
- Maintainer request
- With rewards/contributions we have all of the pieces, but it's post completion vs. something that can be promoted upfront

### How
Rewards will continue to work as it does today, i.e maintainers can embed their badge, get funding and then split the rewards upon completion with any contributors.

However, we'll also introduce the ability for the maintainer to proactively mark an issue with a bounty. 

**Must have**
- [x] They define a split upfront (rewards is the hero/foundations here)
- [x] They can seed it using their personal backer account directly within that module and using the https://github.com/polarsource/polar/issues/1104 model.
- [x] We add an additional embedding at the bottom of the issue + comment about the bounty
- [x] https://github.com/polarsource/polar/issues/1333 (Not coupled with rewards per see, but part of the experience)
- [x] #1347
- [x] #1350
- [x] #1351

**Should have**
- [x] #1352
- [x] https://github.com/polarsource/polar/issues/1329
- [x] #1353

**Could have**
- [ ] Always show "Paid" rewards in backer finance tab with empty state/message "No reward paid out, yet" to clarify the page to new users
- [x] Remove "Payout date" in the finance views

### Prerequisites
https://github.com/polarsource/polar/issues/1104
So that maintainers can seed the bounty if they would want themselves, but only have to pay upon accepted completion.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1125">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1125/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1125/pledge.svg">
</picture>
</a>
