### ISSUE TITLE
🎯 📚 Content & Guides

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1277]
**Subtasks**
- [x] https://github.com/polarsource/polar/issues/1053
- [x] https://github.com/polarsource/polar/issues/1106
- [x] #1234
- [ ] https://github.com/polarsource/polar/issues/1279
