### ISSUE TITLE
🎯 🛠️ Polar API JS SDK

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1280]
**Subtasks**
- [x] https://github.com/polarsource/polar/issues/1122
- [ ] https://github.com/polarsource/polar/issues/1123
- [x] https://github.com/polarsource/polar/issues/1230
