### ISSUE TITLE
🎯 👔 Polar for Teams

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1287]
**Must haves**

- [x] Teams in sidebar
- [x] #1285
- [x] Team members page
- [x] Team settings
- [x] #1500
- [x] #1557
- [x] Spending limits (team and per-member monthly limits)
- [x] Checkout for teams
- [x] #1558
- [x] Billing email

**Should have**
- [x] Notification to admins on funded issues
- [x] #1286
- [x] regularly sync members

**Could have**
- [ ] Notification to admins when a spending limit is reached (?)
- [ ] A signup flow dedicated to teams

**Decision log**

**URL scope**
E.g `/team/<org>/page`
