### ISSUE TITLE
🔋 Sponsors in README

### ISSUE THREAD

**Issue by zegl** [polarsource/polar#1303]
# 👀 What

Many maintainers today are selling space for logos, job ads, and more in their README and websites as a way to passively fund their projects.

It’s also a great motivator to companies to sponsor these projects, as they get more in return from a logo/job ad than a donation would. Ads and recruiting often have a different budget than OSS donations do.

Many projects are doing this manually today, in a process that involves quite a bit of manual overhead, to keep track which sponsors that are still paying for the ad, and updating links, logos, and texts.

---

# 👥 Who

Maintainer

---

# 🚢 How

**Must have**

- [x] As a “tier” in monthly subscriptions, offer “ads/logo” as a thightly integrated tier
- [x] Subscribers of this tier can update images and other assets as a part of their subscription settings
- [x] Public API
- [x] Copy-pasteable sponsors section (on polar.sh)
- [ ] Copy-pasteable thank you section (on polar.sh)

**Should have**

- [x] Automatic generation and updates of the README
- [ ] <iframe> embed for sponsors
- [ ] <iframe> embed for thank yous

**Could have**

- [ ] Text-only ads (job ads?)

# 📓 Decision log

**How is this offered to backers/business?**

Through Monthly Subscriptions (#1291) as custom tiers.

**What customisation do we offer to the maintainer?**

Which price levels that each type of ad should enable.

Example:

- $100 – Small logo
- $500 – Large logo

To make things simple, we should only offer fixed sizes of images. 100x240 seems to be a popular size for “banners”. 60x200 for large logos. 60x140 for smaller logos.

**What customisation do we offer to the subscriber?**

- Image (in different sizes), link, alt text.

**How does the user integrate the ads into their README?**

Up for discussion, but I think a good idea would be to offer a GitHub Action that can run in each repository where the logos should be.

The Action can auto-commit the results, or alternatively, [[send a PR](https://github.com/marketplace/actions/create-pull-request)](https://github.com/marketplace/actions/create-pull-request) automatically with the changes.

In addition to the Action, we should also offer a copy-paste:able generation from the maintainer dashboard on Polar.sh, so that the maintainer can get started without adding the Action. (And help position the ads in the README!)

We should also offer a public API for other custom integrations.

**Who can sponsor?**

All sponsors and logos are subject to review by the maintainers (or by Polar?). If the sponsor is adding NSWF content the logo will be taken down (no refunds). 

**Should we a "hall-of-fame" section?**

Yes, we should have an optional feature to show a hall of fame of historical sponsors (individual and corporate), as a list of avatars in the README. Sorted by total funding amount.

We'd probably want to have this as a separate "embed", as it's popular to showcase sponsors early in the README, and "thank yous" further towards the end.
