### ISSUE TITLE
Show rewards module in public funding page

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1329]
<img width="416" alt="image" src="https://github.com/polarsource/polar/assets/281715/02c32b7d-4c45-4d01-aec9-38f2cf367739">

Add the Rewards context to the funding page. Showcasing:
- [x] Promotion of the upfront reward set
- [x] Pill of contributors rewarded - if done
- [x] Pill of assigned contributors - if assignees on GitHub issue (helpful to leverage assignee to avoid unclear race conditions)
- [x] Integrate the timeline references (PRs etc) that we have in our dashboard etc
