### ISSUE TITLE
Ensure Stripe sends invoice emails directly on completed issues

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1351]
**Todo**
1. [x] Ensure correct Stripe settings
2. [x] Automate invoice creation on issue marked as completed
3. [x] Test end-to-end unfortunately in production since emails are not available with Stripe in development :(
