### ISSUE TITLE
Autosuggest contributors in rewards prompt

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1352]
<img width="772" alt="image" src="https://github.com/polarsource/polar/assets/281715/d9f87aa8-06ad-4b0d-960a-e76cd7f13c68">

We want to make it easier for the maintainer to split the rewards vs. manually entering contributors.

**Todo**
- [x] Auto populate list of contributors in the form: Maintainer (first - always), assignees & contributors (from references we track, i.e PRs etc)
- [x] Split default: Evenly split. In case of upfront reward, respect the maintainer cut for the maintainer and evenly split the rest
- [ ] Nice-to-have: Remove suggested contributor. However, until we have this, 0% should be the same thing. Let's only make sure to exclude contributors with 0% in the comment suggestion here https://github.com/polarsource/polar/issues/1347
