### ISSUE TITLE
Integrate Loops API to trigger marketing email

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#1368]
*This supersedes #1304 in the #1292 project*

---

After several internal discussions, we chose to rely on a dedicated marketing emailing tool to send activation/reactivation emails.

We would like to give [Loops.so](https://loops.so/) a go. To start integrating it, we'll need to:

* [x] Implement a light API client
* [x] Forward contact data on user's registration.
* [x] Update contact data when some events happen:
    * `is_backer` (`bool`)
    * `is_maintainer` (`bool`)
    * `organization_installed`/`repository_installed` (`bool`)
    * `issue_badged` (`bool`)
* [x] Create a migration script to include existing users 

With this, we should be able to put up the onboarding emails loop.

---

Regarding reactivation, we'll need to come up with *hacky* solutions to circumvent Loops limitations. Indeed, they *do not support* (yet?) objects or arrays, so it's not possible to have highly dynamic email content.

I'll open a support ticket to ask what they could recommend us. What I thought could be to have repeated properties in hard*:

* `issue_1_title` / `issue_1_reacts` / `issue_1_url` / `issue_1_badge_url`
* `issue_2_title` / `issue_2_reacts` / `issue_2_url` / `issue_2_badge_url`
* `issue_3_title` / `issue_3_reacts` / `issue_3_url` / `issue_3_badge_url`

Then, we could define a scheduled task sending the event to Loops with those properties.

<sup>*Like when I was a first-year CS student designing a DB not knowing yet of foreign keys and JOIN 🤫</sup>
