### ISSUE TITLE
Disputing a fix/payout

### ISSUE THREAD

**Issue by zegl** [polarsource/polar#169]
In #67 and #71 we've been talking about disputing fixes and payouts, but it's not something we have yet, how should we handle it in the alpha/beta?

Should we:

1) Do it manually. "Reply to this email if you're unhappy with the fix, and want to dispute it." We could also add information to FAQ and ToS pages.

2) Handle it in the app. A button/form where the pledger can send in a dispute.

## TODO

- [x] allow to mark as disputed from backoffice (support flow)
- [x] resolve a dispute from backoffice (refund or pay out)
- [x] add failsafe to refuse payouts of disputed pledges
