### ISSUE TITLE
🎯💰 Accounting

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#1727]
# 👀 What

With Subscriptions incoming, we'll likely need features to help us track of the money that gets in and out.

The goal here is to keep track of all the necessary data we need to be compliant in terms of accounting. Typically, it'll allow us to implement in the future "self-billing" features.

# 👥 Who

Polar

# 🚢 How

******************Must have******************

* [x] Have a single source of truth for the money we receive and the money we transfer
* [x] Each item should be precisely tied to the "product" it comes from, i.e. a specific pledge or subscription
* [x] Keep track for payments of the origin user/organization and its country of origin 
* [x] Handle refunds
* [x] Handle disputes

**Should have**

* [x] Implement a dedicated API so the maintainer can keep track of their money flows. Ideally, it would become the underlying backend for the *Finance* page.
* [ ] Migrate `PledgeTransaction` logic to this new common schema

**Could have**

# 📓 Decision log

**What form should it take?**

It seems rather straightforward to think of it as a single SQL table. Easy to query and easy to export.

**Shall we handle compound transfers?**

Likely, incoming items will come from a single *product* (either a subscription renewal or a pledge).

However, it might not be the same for outgoing items. Typically, in the context of Open Collective, we'll likely make a single transfer at the end of the period that sums up a bunch of subscriptions/pledges. Still, we would like to know each individual items it's made of.

We'll then probably need a one-to-many relationship. Preliminary SQL schema design to come later to clarify this.

**What about `PledgeTransaction`?**

Today, `PledgeTransaction` has mostly the same role, but for pledges only. This new system will probably supersede it, so it makes sense to migrate `PledgeTransaction` logic (+ existing data) to this new approach. The goal is to have a global, common way to track money.

**Comment by frankie567** [comment]
*Those are ongoing notes about the implementation. Subject to frequent changes.*

---

```mermaid
classDiagram
        class Transaction {
            UUID id
            datetime created_at
            UUID account_id
            str currency
            int amount
            UUID? pledge_id
            UUID? issue_reward_id
            UUID? subscription_id
            UUID? transfer_id
        }
        class Transfer {
            UUID id
            datetime created_at
            str? stripe_transfer_id
        }
        class TransferTransaction {
            UUID transaction_id
            UUID transfer_id
        }
    Transaction ..> Transfer
    Transaction --> TransferTransaction
    TransferTransaction --> Transfer
```

---

`Transaction` is the core object all money flows to and from a maintainer's `Account`. It can be related to:

* A `Pledge`
* An `IssueReward`
* A `Subscription`
* A `Transfer`

`Transfer` represents the operation of us, Polar, transferring the money to the maintainer. It can represent several operations. That's why there is a many-to-many table, `TransferTransaction`, which gives, for a single transfer, all the transactions it's related to.

---

Toy example:

## 1. Polar receives 100 $ + 20 VAT $ from a subscription. The maintainer gets 10% of the amount, VAT excluded.

**Transaction**

| id | account_id            | currency | amount | pledge_id | issue_reward_id | subscription_id | transfer_id |
|----|-----------------------|----------|--------|-----------|-----------------|-----------------|-------------|
| T1 | MAINTAINER_ACCOUNT_ID | usd      | 9000   |           |                 | SUB_ID          |             |

## 2. Polar receives 10$ + 0 VAT $ from a pledge. The maintainer gets 10% of the amount, VAT excluded.

**Transaction**

| id | account_id            | currency | amount | pledge_id | issue_reward_id | subscription_id | transfer_id |
|----|-----------------------|----------|--------|-----------|-----------------|-----------------|-------------|
| T1 | MAINTAINER_ACCOUNT_ID | usd      | 9000   |           |                 | SUB_ID          |             |
| T2 | MAINTAINER_ACCOUNT_ID | usd      | 900    | PLEDGE_ID |                 |                 |             |

## 3. Polar generates a transfer to the maintainer account.

**Transaction**

| id | account_id            | currency | amount | pledge_id | issue_reward_id | subscription_id | transfer_id |
|----|-----------------------|----------|--------|-----------|-----------------|-----------------|-------------|
| T1 | MAINTAINER_ACCOUNT_ID | usd      | 9000   |           |                 | SUB_ID          |             |
| T2 | MAINTAINER_ACCOUNT_ID | usd      | 900    | PLEDGE_ID |                 |                 |             |
| T3 | MAINTAINER_ACCOUNT_ID | usd      | -9900   |           |                 |                 | TF1        |

**Transfer**

| id  | stripe_transfer_id | 
|-----|--------------------|
| TF1 |                    |

**TransferTransaction**

| transfer_id | transaction_id |
|-------------|----------------|
| TF1         | T1             |
| TF1         | T2             |

At the end, the maintainer account's balance is at zero.

---

For self-billing, we can simply take the `Transfer` object and generate an invoice corresponding to that amount. We have access to the details of each item through `TransferTransaction`.

**Comment by frankie567** [comment]
With Stripe, it's easy to get fees for payments (directly accessible from `BalanceTransaction`).

However, it also bills fees for some transfers (cross-border) and payouts. The problem is that it doesn't give us a detailed amount per transfer/payout: it generates a single `BalanceTransaction` that bills the fees for a whole month. Example:

```
    {
      "amount": -47,
      "available_on": 1688200476,
      "created": 1688200476,
      "currency": "usd",
      "description": "Connect (2023-06-01 - 2023-06-30): Payout Fee",
      "exchange_rate": null,
      "fee": 0,
      "fee_details": [],
      "id": "txn_1NOzGKDG1jUQrXwCTaIZTlOE",
      "net": -47,
      "object": "balance_transaction",
      "reporting_category": "fee",
      "source": null,
      "status": "available",
      "type": "stripe_fee"
    },
    {
      "amount": -5,
      "available_on": 1688200410,
      "created": 1688200410,
      "currency": "usd",
      "description": "Connect (2023-06-01 - 2023-06-30): Cross-Border Transfers",
      "exchange_rate": null,
      "fee": 0,
      "fee_details": [],
      "id": "txn_1NOzFGDG1jUQrXwCreiAPa2K",
      "net": -5,
      "object": "balance_transaction",
      "reporting_category": "fee",
      "source": null,
      "status": "available",
      "type": "stripe_fee"
    },
```

Therefore, it's difficult to tie it to a specific transfer/payout in our DB
