### ISSUE TITLE
🎯 📝  Posts

### ISSUE THREAD

**Issue by zegl** [polarsource/polar#1748]
# Posts Design Document

## Intent

Posts are a way for open source maintainers to communicate with their community & contributors. These posts are long-form documents written in a JSX-capable version of Markdown called MDX.

### Posts

Posts are associated with an Organization (including personal Organization) and has an associated author/user. A new post can be saved as a draft or published directly from the "New Post" view. 

When creating a new Post, the author can configure the following:

- Title
  - Slug generated from title
- MDX Content
  - Edit / Preview capabilities
- Audience
  - Public
  - Paying Subscribers
- Publish Configuration
  - Publish Now
  - Publish at Date & Time
  - Option to send email to subscribers upon publication (True by default)

#### MDX Components

Authors can utilize a few custom JSX-components which are provided by the Polar-platform.

**Subscription Upsell**
The subscription upsell-component can be used to upsell subscription tiers. 

```
<SubscriptionUpsell />
```

**Paywall**
You can mark a section of the post as paywalled content. This will ensure that only paying subscribers can access the content inside.

```
<Paywall>
{/** Here goes my paywalled content */}
</Paywall>
```

**Ad**
Using the Ad-component, you can easily surface ads in your posts. Ads can be used to promote a maintainer or a specific repository.

```
<Ad organization="" repository="" />
```

### Emails

Posts are by default delivered to its subscribers by email. This setting can be configured in settings. Emails are **only** sent 5 minutes after a post has been published, to allow for a small time window where edits & adjustments can be made before its delivered to users inbox. Emails are never sent on subsequent edits on a post which previously has been sent out to its subscribers.

### Maintainer View

Posts are surfaced in chronological order on the Maintainer page. 

### Analytics

Analytics for Posts are gathered for the maintainer in the following ways:

- Post opened on the web
- Post opened in email

#### Must have

- [x] Create API
- [x] Get API 
- [x] Lookup API 
- [x] Search API 
- [x] Update API
- [x] Send as email

#### Could have?

- [x] Scheduled posts
- [x] Web views tracking
- [x] Preview/test email 
- [x] OG images
- [x] `<SubscribeNow />` component
- [x] Embed: Issue
- [x] Embed: YouTube
- [ ] Embed: Twitter?
- [x] Pre-authenticated links when sending as email
- [x] User editable slug

#### Later

- [x] Delete API
- Email opens tracking
- Comments
- Import / export subscribers

**Comment by zegl** [comment]
🥇
