### ISSUE TITLE
Built-in free subscription tier

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#1749]
We want an easy way for users to follow/subscribe to maintainers, especially so they can follow their posts.

Currently, it's possible to have free subscription tier but it suffers from the following limitations:

* The maintainer has to create such subscription tier and set the price to zero.
* The subscription process is the same and goes through Stripe (with a simplified form nonetheless)

As it'll be core to Polar experience, we would like to streamline this:

* [ ] Create a free subscription tier by default — with it's own type so it's easy to identify it and apply special logic in backend/frontend
    * [ ] In combination with #1748, add a benefit on this tier granting access to the default post audience 
* [ ] Have a dedicated subscription flow for this tier that doesn't go through Stripe. It means:
    * [ ] A specific API which would expect either a logged-in user or an email address
    * [ ] Create a `Subscription` object directly without any time limitation and not tied to a Stripe subscription

**Comment by birkjernstrom** [comment]
Thanks for adding this to the backlog @frankie567. I've removed (strikethrough) the task around tying access to posts via benefits. Why?

Starting simple, we'll only offer segmenting posts by Free or Paid (any paid subscription). We believe that will be the most common use case to start. However, we (or I at least) expect additional segmentation to become a feature request. We can then later expand the product to allow the maintainer to select a certain tier(s) they want it to be accessible for. Or chose to filter by benefit, i.e if they have multiple benefits of type "premium post", e.g "Educational material", "Roadmap Updates" or what have you.

So initially, we're not going to tie the logic to benefits. Just paid subscriptions (binary) to unlock paid content. 

With this said, we should still create the "premium post" type of benefit. Just that it will be more of a social construct and marketing upsell the maintainer can customize for their paid tiers vs. technically required to unlock such access beyond the paid subscription itself. Later, in case we add additional filtering based on tiers/benefits, we could promote the maintainer to create different versions of it that they can then use in filtering.

I hope my explanation makes sense? Let me know if not and I can share a Loom talking it through instead :)

**Comment by frankie567** [comment]
I understand, @birkjernstrom, but, to be honest, I don't agree with this approach.

It looks like we'll need to have **specific logic to check if the user has an active (paid) subscription or not** to grant him access to the posts. Said another way, we totally bypass the Benefits system which is *exactly* designed for this, i.e. grant access to *things* depending on your subscription.

I don't really see why it would be more difficult/time-consuming to just create the benefit and tie it to the Post logic than tinkering with a dummy one.

---

The way I see it, we would have two main objects:

* Post
* Audience

A `Post` is tied to an `Audience` and an `Organization` (i.e. maintainer).

An `Audience` is tied to an `Organization` (i.e. maintainer) and to one or several `User` (i.e. people who can read the posts).

At first, we can pre-create two `Audience` (Free and Premium) for each `Organization` and not let the user create/modify them.

Then, we can implement a `PostBenefit` which would have a single parameter: which `Audience` it grants access to. The granting logic is quite straightforward: add the newly subscribed user to the `Audience`.

To display posts to the user, we'll just need to make a query filtering the posts for the `Audience` there are into.

---

That looks pretty straightforward to me and would lay pretty solid foundations for future expansions of this feature. Besides, it would be a great demonstration of what we can achieve with the benefits system.
