### ISSUE TITLE
🎯👋🏼 Progressive Onboarding

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1818]
# 👀 What

Revamp our onboarding given expansion to Subscriptions & Posts and additional capabilities. Leverage the opportunity to great more of a progressive onboarding to make the product easier to understand and gradually unlock features. 

[<img width="1052" alt="image" src="https://github.com/polarsource/polar/assets/281715/af7f2dae-1019-443b-83ba-7ae10ffc21d5">](https://www.loom.com/share/12797017b49b469692043084a5281ce8)

👥 **Audience:** Everyone

# 🚢 How

User story below is from the most basic type of account to one upgrading to use all Polar has to offer. Showcasing the entire flow (progressive) and highlighting different entry points.

## Email Subscriber ➡️ GitHub User (Backers)
<img width="1193" alt="image" src="https://github.com/polarsource/polar/assets/281715/f1b0ec61-259b-45db-8208-1dc24f68f08b">

1. User sees a post shared on Twitter/X from a maintainer
2. User comes to the post page on the maintainers Polar site
3. User can subscribe (Free) with their email only
4. Gets upsold additional tiers once they're subscribed - can skip
5. Receives an email in the future for another post from the maintainer
6. Clicks it
7. Reads post online & logged in (links contain magic link tokens ~1 week TTL)
8. Sees their profile in the top-right corner: Anonymous profile photo, but access to dashboard links, e.g feed, funding etc.
9. In the profile picker & dashboard we heavily upsell GitHub Connect to access more features and a better experience

**Must have**
- [x] Free Subscription with email-only
- [x] Ability to sign-in to Polar using email-only to access feed/subscriptions
- [x] Upsell in Dashboard Sidebar to connect GitHub

**Should have**
- Upsell page to additional tiers after Free subscription with email
- Automatic magic link tokens in post links
- Upsell on Feed page to connect GitHub

## GitHub User ➡️ Creator/Maintainer
<img width="1319" alt="image" src="https://github.com/polarsource/polar/assets/281715/0135d248-eddb-4cc0-8142-1ff85b141dba">

User gets to this point when signing up to Polar directly with GitHub (backer, e.g funding flow) or upgrading to GitHub (previous flow) from email-only.

1. User sees the backer navigation in the dashboard, feed, funding page etc.
2. User sees an upsell to use Polar as a maintainer/creator in the sidebar
3. User enables the maintainer/creator features for their org (personal | org)
4. We enable the `maintainer` flag on the specific profile (personal/org) and showcase the maintainer/creator navigation

*Note:* No GitHub installation is required or promoted at this stage. Since Subscriptions & Posts can be used without it and a barebones GitHub login profile. We only request it once it's needed, i.e issue funding.

**Must have**
- [x] Maintainer upsell card in the sidebar for backers
- [ ] Store `maintainer=(true|false)` flag for person/org. Upsell card to set this to `true` once activated.
- [ ] Support signup with GitHub as a maintainer/creator directly, i.e setting the flag to `true` immediately. To be used on our public website where we have CTAs for maintainers specifically vs. having an additional step here.
- [ ] Migration script to set the flag to `true` for all accounts with repositories today, i.e our current maintainers. 

**Should have**
- Show top 3 (stars) open repositories we can find for the GitHub user and showcase them in our upsell card. Creating a more personal upsell. Supporting a fallback version if we don't have this, i.e default implementation.

**Could have**
- Welcome screen for new maintainers/creators in the dashboard. 

## Creator/maintainer with issue funding

Once the user has enabled maintainer/creator mode they can use subscriptions & posts directly. They'll also see issues in the navigation. 

1. User with maintainer/creator mode activated clicks `Issues` in nav
2. User sees a new onboarding view for issues. They can see our badge embed on an example issue along with a brief pitch what it offers. Followed by an upsell to connect repositories to activate it for them.
3. User clicks "Connect Repositories" and initiates the GitHub installation flow. Selecting desired repositories over at GitHub before being redirected back to Polar (same intermediate setup/initialize page as today)
4. Once they click "Save" on the initialize page, they're redirected back to their dashboard in the issues page with their connected repositories & issues.
5. We move the "Promote" pages into the issues tab as sub navigation items, e.g "Badge Settings" & "Promote" (Embeds). Moving the search, filters etc as a row underneath.

**Must have**
- [ ] Onboarding (empty state) page in issues for maintainer/creator without connected repositories. Showcasing value/example + upsell to connect repositories.
- [ ] Move current "Promote" page into "Issues" as sub-navigation "Repositories" (Badge & Repo settings for funding) & "Promote" with the embeds.
- [x] Move repo filter, search and sorting row underneath the new page title and sub navigation header
- [ ] Add ability to connect more repositories within the "Repositories" sub-navigation

**Could have**
- Good opportunity to move "Save"-button above the list of repositories in case it's a long one

## Connect Org
<img width="1262" alt="image" src="https://github.com/polarsource/polar/assets/281715/828ba207-9c88-4b02-ad46-17c3e659866c">

1. A GitHub user (backer or maintainer/creator) can click "Add organization"  at the bottom of their profile picker
2. We create a dedicated (outside dashboard) page, i.e similar to our initialize repo page, to create & connect a new organization.
3. User can see an upsell of benefits of connecting an organization, i.e enabling funding on its behalf, creating a maintainer/creator page for it etc. 
4. User is asked to select which features they want to use the organization for, i.e Funding and/or Creator. Checkboxes to enable both or one of them. Once at least one is selected, we enable...
5. User can click "Connect GitHub Organization"
6. Redirected to GitHub to connect org & install repo.
7. Redirected back to Polar dashboard for the newly connected organization (profile picker)

**Must have**
- [x] Onboarding page for connecting new organization. User can choose to connect it for creator and/or funding mode upfront. Ensuring we don't have an empty dashboard
- [x] Show creator upsell as we do for backers if they don't have it enabled
- [ ] Show funding upsell if they opted in for the creator mode only
- [ ] Hide centralized billing behind a feature flag. So organizations can be created for funding, but only support "Fund on behalf of" for their team (expenses). Allowing me/us to enable the feature flag for centralized billing for a few select teams first behind the scenes.
- [ ] Ability to leverage our GitHub installation flow, but with a different redirect (internally) than showing repo initialization (issue funding) in this flow

# 📓 Decision log

**What should we call `maintainers` & `backers` going forward?**
TBD. But we're stretching both use cases now and the terminology doesn't feel right. We should stick to the same within our code to avoid having 4 terms, but might want to communicate something different in the UI, e.g `Creator` instead of `Maintainer`.
