### ISSUE TITLE
🎯 Import Subscribers

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1858]
# 👀 What

Ability for maintainers to import subscribers (email addresses) for their different subscription tiers – free by default. Allowing them to move over fully to Polar + manually & easily sync some premium subscribers, e.g sponsors on GitHub, to specific tiers and thereby be able to manage Polar as the central platform for everything vs. spread out.

[![Image](https://github.com/polarsource/polar/assets/281715/a0c8b4aa-0c91-47f9-967a-811839288141)](https://www.loom.com/share/57a75ba4ba08471aa423aa870d2be0e5)

👥 **Audience:** Maintainers

# 🚢 How

1. On the "Subscribers" page underneath Subscription, maintainers would see a "+ Import"-button
2. A modal is shown to upload a CSV OR simply a textarea to dump all emails (\n or , separated) and a dropdown to select tier (free by default)
3. Click "Import" and see them imported as subscribers for those tiers

**Must have**
- [x] Modal to import subscribers to a selected tier
- [x] We tie them to a Polar user in case we have a verified account with a provided email in the list
- [x] Otherwise, we treat them as unverified email accounts

# 📓 Decision log

**Upload subscribers via CSV or in an input field?**
TBD

**Comment by zegl** [comment]
Done in #1836 and #1945
