### ISSUE TITLE
🎯 🔁 Business Subscriptions

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1859]
# 👀 What

Support subscribing as an organization to tiers of group "Pro" and "Business"; user can select org to subscribe as in a dropdown in connection with the subscription action for the tier. Granting access to benefits for their members (TBD - See decision log on this).

[![Image](https://github.com/polarsource/polar/assets/281715/90e51ee7-6d41-47c4-8fa0-41f4b9d372e8)](https://www.loom.com/share/0c4ab11847314575851938885897d714)

👥 **Audience:** Everyone

# 🚢 How

**Must have**
- [x] Select organization to subscribe as in connection with "Pro" & "Business" tiers
- [x] Show organization in maintainers "Subscribers"-view (including a count of members?)

**Should have**
- [ ] Ability to set a maximum amount of supported members in the tier settings 

**Could have (See decision log re: team member access)**
- [x] Grant benefit access to all team members
- [x] Revoke benefit access to all team members (unsubscribe)
- [ ] Support to limit benefits to organization admins vs. all, e.g future benefits like logotype in README etc
- [x] Incrementally update benefit access to users as team updates, e.g members join, leave etc.

# 📓 Decision log

**🚨 How does team members access benefits, e.g premium posts?**
Our solution is to grant the benefit to all members of an organization, i.e each member would get the premium posts in their own - personal - feed. Of course, this is up to each benefit and how it implements the `grant` logic for a subscribed organization and a particular organization member, e.g future benefits might only grant access in case the member is an admin (logotype placement management as an example). Nonetheless, this approach gives ultimate flexibility to each benefit how it's best surfaced and to whom within an organization, and avoids the user having to jump around multiple profiles to experience them all.

In the future, we might want to add clarifications in the feed/benefits that the user has access to them because their organization is a subscriber. Combined with ability to mute, hide etc. Or even that it would require more of an opt-in for the user, e.g "You can get premium updates from [developer] because your organization is subscribed. Opt-in". TBD and not a concern now at this early stage until feeds start getting out of hand 🙂

**Comment by frankie567** [comment]
>🚨 How does team members access benefits, e.g premium posts?
Early in our discussions of Feed, we had the idea of your personal feed including content/benefits from maintainers that you have access to because an org you're a part of has subscribed. However, I believe we decided on separating them. Having a feed unique per user/org, e.g making your personal feed truly personal and separate from your work feed for instance. I believe this is cleaner and more aligned with what users would expect. It also greatly simplifies benefit grants. Not having to automatically grant access to all team members, but the organization, and by consequence members would gain access when viewing the feed from the org.

Unless I'm mistaken, I think we changed our mind about this in our last demo meeting. A user should only have one feed and see all the posts they are directly or indirectly subscribed to. Can you confirm that it was our decision, @birkjernstrom?

In the future, we could maybe add filters to the feed so the user could hide content they don't want.

**Comment by birkjernstrom** [comment]
> Unless I'm mistaken, I think we changed our mind about this in our last demo meeting. A user should only have one feed and see all the posts they are directly or indirectly subscribed to. Can you confirm that it was our decision, @birkjernstrom?
> 
> In the future, we could maybe add filters to the feed so the user could hide content they don't want.

You're not mistaken, but 100% correct. This was a reflection of an earlier conversation before we commenced work on the feed, posts etc. I'm happy we opted for benefits being granted each member and within their own feed. Agree that in the future we can add more controls to manage the feed accordingly, if this ever becomes a problem. I'll update the decision log now to reflect this.

**Comment by emilwidlund** [comment]
@birkjernstrom @frankie567 I'd like to make a case for only allowing organizations to subscribe to business tiers. Allowing an organization to subscribe to Pro-tiers would likely become a way for groups of people to acquire subscriptions for a small amount of money, split between the organization members.

**Comment by frankie567** [comment]
@emilwidlund In the current implementation, there is no restriction upon which tiers an organization can subscribe to (including *Hobby*).

I'm not sure it's necessary to add too many restrictions *right now*, without having seen abuse in the real-world.

Besides, I'm quite reluctant to add business logic to the tier types, which were primarily designed  as a way to display/group tiers rather than bearing specific logic (we are not even 100% sure if those groups are sensible). If we need to integrate features to prevent organizations abuse (again, not convinced it's necessary to tackle this now), I would say it's preferable to have dedicated feature for them (like limiting the number of members, as Birk suggested).
