### ISSUE TITLE
🎯 Feed

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1860]
# 👀 What

Aggregate and show posts chronologically for the given user/org for the subscriptions they have. Combined with an area to feature maintainers to follow - random selection from a static list initially - and ability to one-click follow them.

[![Image](https://github.com/polarsource/polar/assets/281715/c3f6a365-ae82-4cb4-8265-4c79c912fdfe)](https://www.loom.com/share/3408714dd5c74cab84989b025d30e8c7)

👥 **Audience:** Everyone

# 🚢 How

**Must have**
- [ ] Infinite scroll pagination of chronologically sorted posts across all maintainers the user/org subscribes to
- [ ] Aggregation of posts to fetch posts based on permissions, e.g free subscriptions or premium
- [ ] Module to showcase featured maintainers to follow

**Should have**
...

# 📓 Decision log

**🚨 See important discussion related to how where we want to show benefits, i.e posts, for orgs here**
https://github.com/polarsource/polar/issues/1859
