### ISSUE TITLE
🔋 Premium Posts

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1863]
# 👀 What

Create a benefit type for premium posts combined with a solution for how we can easily fetch which users should receive/see certain posts, e.g free or paid, depending on whether they have a subscription AND whether they have the premium post benefit.

Tying https://github.com/polarsource/polar/issues/1748 together with our subscriptions and benefits.

👥 **Audience:** Everyone

# 🚢 How

**Must have**
- [x] Maintainers can add our native premium post benefit to tiers
- [x] Our design supports us recommending this and having it on by default for new tiers
- [x] Maintainer can customize how it's described, i.e we leverage the type vs. have a hardcoded benefit
- [x] Connect it to posts service and it's current model to fetch users to email OR can view online OR in feed

**Should have**
...

# 📓 Decision log

...

**Comment by zegl** [comment]
Looks like it's mission completed here!
