### ISSUE TITLE
Restructure subscription tier types

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#2089]
- [x] Remove Pro Enum
- [x] Rename Hobby Enum to Individual
- [x] Use color schema and icon of Pro for Individual
- [x] Migrate existing Pro tiers to Individal tier type

Context: https://discord.com/channels/1078611507115470849/1192087765031067719

**Comment by emilwidlund** [comment]
🥳

**Comment by birkjernstrom** [comment]
🚀
