### ISSUE TITLE
Polish: Better sorting & filtering of issues

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#220]
![Image](https://user-images.githubusercontent.com/281715/233723075-98bb47cd-c010-4a3c-b483-6518cb1cd547.png)

Currently our sorting matches that of Github with `latest`. Intent is that our default sorting should be based on the combination of:
- Pledged (1st)
- Thumbs-up (2nd)

Essentially a stack rank of the most requested features/issues. Ideally, since we track progress on issues we have the opportunity to sort based on recent activity vs. recently modified (Github). I'd love to introduce a sorting method for "Progress". Perhaps even combing then the "Progress" in the default sorting, i.e combination of what needs to be reviewed along with what should be focused on.

Finally, filtering. I think we should add a filter for "Pledges" to be able to quickly filter out any issues without it.

These efforts will allow us to make the view less "noisy" like Github in our dashboard and allow it to be focused on pledges + prioritized issues by default if maintainers prefers it.

# Subtasks

- [x] new dependencies tab
- [x] issues tab: default sorting by (pledges, thumbs up, updated_at?)
- [x] dependencies tab: default sorting by (state, your pledged amount, updated_at?)
- [ ] add a "pledged" filter to include/exclude issues with pledges

[![Funding with Polar](https://dashboard.polar.sh/api/github/polarsource/polar/issues/220/funding.svg)](https://dashboard.polar.sh/polarsource/polar/issues/220)
