### ISSUE TITLE
One-click creator mode activation

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#2221]
Currently, activating the creator dashboard is a bit cumbersome:
- Click "Get started" in the upsell
- Review separate upsell
- Redirect to GitHub to install repositories - even though it's only required for issues atm
- Onboard those repositories & setup issue funding settings

Going over to progressive onboarding instead to speed things up significantly:
- Click "Get started" 
- You're done
- (Progressively onboard repositories in the issues view to enable that feature)

We can achieve this by creating a lightweight personal organization without installation_id etc. 

**Todo**
- [x] API endpoint to upgrade the user account to creator
- [x] Ensure free subscription tier is created
- [x] Expand organization details from user details
- [x] Add upsell card on issues page for orgs without `installation_id`, i.e no repositories installed (progressive onboarding)
- [x] Avoid fetching non-existing data in issue views when app is not installed
- [x] Upsert org creation since we technically might have a dependency org since before which would raise `IntegrityError`
