### ISSUE TITLE
Badge settings should appear in onboarding

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#25]
It exists, but doesn't show currently. Intent is to show up after 40% synced or a certain time threshold. The fact that it's not showing is likely caused or connected to what's caused #74 

User Story: "After 10 seconds, I understand that Polar is syncing all my issues, but would like to proceed with the product. So I expect the next step in onboarding and/or the ability to click continue"

**Tasks**
- [x] Fix bug of the component not showing
- [x] Change it to show after 10 seconds vs. % saved
- [x] Update to use the new badge settings from dashboard settings built by Gustav

[![Funding with Polar](http://127.0.0.1:3000/api/github/polarsource/polar/issues/25/funding.svg)](http://127.0.0.1:3000/polarsource/polar/issues/25)
