### ISSUE TITLE
Badge settings per repository

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#273]
Decided on April 27th.

![image](https://user-images.githubusercontent.com/281715/234989758-f40d93bc-5445-4634-ad19-c75a8548bfe8.png)

We've decided to improve the badge setting to support on/off per repository. More control is good + makes it less scary to opt-in and try on one repository before enabling it on others.

Nuances:
1. Settings re: design will be global for the organization
2. On/off per repository

In changing the above, we should additionally make sure we only add the badge on open source repositories, e.g
1. `is_private=false`
2. `is_fork=false` (only badge the source repo - at least for now)

**Tasks**
- [ ] Move badge settings to repo (on/off / repo)
- [ ] Remove backer profiles (feature for later)
- [ ] Update Badge design
- [ ] Update onboarding flow in accordance w. Petter discussion to make it more clear
- [ ] Integrate new onboarding into settings
- [ ] On new repo: Default to “off” setting
