### ISSUE TITLE
Implement the badge design

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#334]
Ideally, we could generate the SVG dynamically using <text> (pledge amount) and <image> (pledgers - in the future) tags vs. using Satori. Ensuring that the design is always 1:1. 

Otherwise, we need to update the Satori implementation to reflect the recent design and ensuring it's not cached.

**Tasks**
- [x] Implement dynamic SVG (vs. Satori – ideally) of new design
- [x] Ensure we set appropriate cache headers (no cache)
- [x] Implement support for dark mode (See https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/)

# Light

![Badge](https://dashboard.polar.sh/api/github/polarsource/polar/issues/334/pledge.svg)

# Dark

![Badge](https://dashboard.polar.sh/api/github/polarsource/polar/issues/334/pledge.svg?darkmode=1)

# Dynamic <picture>

<a href="https://polar.sh">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://dashboard.polar.sh/api/github/polarsource/polar/issues/334/pledge.svg?darkmode=1">
  <img alt="Text changing depending on mode. Light: 'So light!' Dark: 'So dark!'" src="https://dashboard.polar.sh/api/github/polarsource/polar/issues/334/pledge.svg">
</picture>
</a>

# From app 👇 

[![Fund with Polar](https://dashboard.polar.sh/api/github/polarsource/polar/issues/334/pledge.svg#ff)](https://dashboard.polar.sh/polarsource/polar/issues/334)
