### ISSUE TITLE
Dashboard pledge should link to public page + remove CC on file (for now)

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#531]
We've decided to remove this feature for now to avoid confusion and risky outcomes. It might not be entirely clear that you save a CC on file for the entire organization and potentially not the right approach vs. individual cards (expenses). 

Instead, we'll re-introduce this more properly through a combination of later efforts, e.g:
1) Save personal CC on file
2) Team management / budgets (more explicit and intentional)

**Todo now**
- [x] Remove CC on file from settings and our API
- [x] "Pledge" in dashboard view should link to public pledge page
- [x] No animation for the "Pledge" button in the dashboard (don't hide it)
- [x] Redirect to dashboard dependency view
- [x] Show success toast in dashboard if pledge was successful
- [x] Switch to redirect from `/status` page + Zustand store. Cleaner and simpler logic.
- [x] Test Stripe "0" HTTP calls in `main` and compare against this branch. Seems excessive. Wondering if it's always been like this

**Comment by birkjernstrom** [comment]
Keeping API for now since team management will be a priority.

I removed the `PledgeOverlay` though. Since I quite liked the experience of linking out to a dedicated pledge page + concept of having one component/space for it as we expand functionality in the future.

**Comment by birkjernstrom** [comment]
Went ahead and removed it since I had to change the API. Would be confusing with some changes to existing methods and retaining former – now dead – code paths. Linked to this issue + PR in the roadmap item instead to be able to cherrypick stuff back once we get there.
