### ISSUE TITLE
Improve issue sorting

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#561]
Got some great feedback from Samuel. We should allow sorting by "Most reactions" (not only thumbs-up) and our default "Most wanted" should be by pledge and then the combination of total reactions + comments (total engagement).

- [x] calculate engagement and positive reactions and save in db (#676)
- [x] add new sorting to API (#680)
- [x] add "Most reactions" sorting to app (#681)
