### ISSUE TITLE
Manually badge & promote an issue

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#656]
## Depends on:
https://github.com/polarsource/polar/issues/719

![image](https://github.com/polarsource/polar/assets/281715/140dce38-7d01-4374-acc4-ab5343e11e08)
**Note: ** Not final design. Petter is updating the context design as per #719

**Todo**
- [x] Support badging an issue from the dashboard. See https://github.com/orgs/polarsource/discussions/558
- [x] Support customizing badge context for this issue specifically.
- [x] Allow for edits of the above (single issues)
- [x] Ability to remove badge from currently badged issues via modal
- [x] Ability to post a Github comment with the badge as well (notify watchers + latest in historical issues w. a lot of comments)
- [x] Ability to copy link to issue to share elsewhere
- [x] Ability to copy Badge SVG (Light/Dark/Both) themes
- [x] Posthog events for 1) embedding & 2) editing & 3) removing + adding a Github comment, copying SVG & copying share URL 

**Limitations / Tradeoffs**
- [ ] Discuss: How to showcase this in our Browser Extension on Github. _Can be a separate task._
