### ISSUE TITLE
Maintainer to confirm "Completed" issue

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#664]
Once an issue is closed with pledges behind it, we should prompt the maintainer (notification + email + in-app action) to confirm that it's considered completed incl. providing a custom note to backers (optional).

**Todo**
- [x] Rename "Completed" to "Closed" for issues to map our language with Github (avoid cognitive overhead & confusion) #745
- [ ] Introduce `confirmation_pending` on pledges for issues that have been closed
_See this discussion for some good context about this design choice: https://github.com/polarsource/polar/issues/568_  #750
- [ ] Design how issues should be confirmed completed in dashboard / extension @petterheterjag 
- [ ] Implement the design
- [ ] Send notification to maintainer once issues are closed with pledges – nudge for them to confirm completion

**Comment by petterheterjag** [comment]
Design: https://www.figma.com/file/XyFpx0vdHk6bfWYLWmOHSC/Polar-Mega-File?type=design&node-id=2757-73650&t=UVPOj63BD7o8NKw3-4

Notes:
- There are three parts of the prompt: a notification in the dashboard, a button added to the pledge part of the issue and an email (needs copy).
- When pressed, the "Mark as solved" button should change styling and say "Marked as solved". We can work out how this should look together.

**Comment by hult** [comment]
In back office, we can currently mark a pledge in state `created` as `pending`. How should we deal with this going forward? Seems like marking it as `confirmation_pending` has very little effect? Should we keep mark as `pending`, allowing back office to bypass `confirmation_pending`?

**Comment by birkjernstrom** [comment]
I think we should also rename these states. Not a priority now (scope creep too for this issue). Just a note to self for the future. I find they add cognitive overhead to grasp each time I review them, or just me? :-)

**Comment by hult** [comment]
Absolutely agree about the renaming, super confusing
