### ISSUE TITLE
Alpha/Beta Invites

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#82]
We want to limit and ease our initial rollout using classical beta invites. 

Of course, since our badge is exposed to everyone, we need to allow pledgers to get invited for a customer/following account without any invite except for their initial pledge. This can create an interesting and fun dynamic in case we grant invites to each member; pledging becomes a way to get early access which in turn also reaches out to new maintainers (from their issue dependencies).

- [x] allow to join with code
- [ ] send codes via email to others
- [x] auto approve from logged in pledge?
- [x] auto approve users joining from anon pledge
- [x] generate codes on backoffice

**Tasks**
- #122 
- #123

[![Funding with Polar](http://127.0.0.1:3000/api/github/polarsource/polar/issues/82/funding.svg)](http://127.0.0.1:3000/polarsource/polar/issues/82)
