### ISSUE TITLE
Set & show funding goal

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#898]
Ability to have specific funding goals for issues vs. it being 100% open-ended.

### Maintainer

- [x] ~~Can set a default funding goal for badges (onboarding/settings). Similar to min. funding today.~~
- [x] Can customize this for individual issues in our badge settings modal / issue
- [x] Can see progress towards a goal in their issue backlog on Polar

**Could have**
- [ ] #1288

### Backer
- [x] Can see the funding goal & progress in the badge
- [x] Can see it on the funding page. Bonus: Showcasing what their contribution would mean

**Could have**
- [x] #1289

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/898">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/898/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/898/pledge.svg">
</picture>
</a>
