### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#9]
<img width="540" alt="image" src="https://user-images.githubusercontent.com/281715/220884871-c0aa8d02-2c15-456d-8c1a-0a07632bb756.png">
<img width="805" alt="image" src="https://user-images.githubusercontent.com/281715/220884991-cd9f5af9-fda4-4e0c-969e-c467e3188238.png">

## Prerequisites

1. Context/Global state of current `organization` and `repository` for user & SSE events

## Todo

- [ ] Introduce settings for organization
- [ ] Redirect user to onboarding in case no settings exists for an organization, i.e it was just installed and we're syncing all its repositories 
- [ ] Keep track of issues synced in database
- [ ] Showcase all repositories
- [ ] Update them based on SSE events of newly synced issues, i.e progress
- [ ] Allow user to customize and set settings for organization
