### ISSUE TITLE
[POL-55] Milestones

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#926]
- [ ] Support creating and editing milestones in the polar web app
- [ ] Milestones are attached to a repository
- [ ] Milestones are visible on the public org and repo pages (https://polar.sh/polarsource)
- [ ] Milestones can receive pledges
- [ ] Milestones are optionally tied to a GitHub milestone. When connected to a GitHub milestone, issues tied to the milestone are listed whenever the milestone is shown.
- [ ] Milestones can have a funding goal and a deadline

# Questions

* Do milestones have their own public pages? `/[org]/[repo]/milestones/[slug]`?
* When is the milestone completed? Manually by maintainers?
* What happens at the deadline?

# Design proposals

<img width="1511" alt="Frame 848" src="https://github.com/polarsource/polar/assets/47952/484bc524-8d85-4456-9a34-d642cba3a6de">
<img width="1511" alt="Frame 834" src="https://github.com/polarsource/polar/assets/47952/97e77ffb-9054-46bc-9037-770ada4b1e9b">
<img width="1512" alt="Frame 954" src="https://github.com/polarsource/polar/assets/47952/57c16441-b0e7-4940-bfd6-be871ac8d098">

<sub>[POL-55](https://linear.app/polar-sh/issue/POL-55)</sub>

**Comment by birkjernstrom** [comment]
New backlog/definition to be created via Linear. Closing this for now to clean things up.
