### ISSUE TITLE
Separate maintainer & backer dashboard

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#927]
Implement separation of maintainer & backer modes and views. Currently, they're coupled and it's not great. Separate modes creates clarity + we'll have different onboarding/functionality for them.

**Maintainer**
<img width="898" alt="image" src="https://github.com/polarsource/polar/assets/281715/1156c953-9b63-47c2-a469-297cb0b0e5aa">

**Backer**
<img width="1024" alt="image" src="https://github.com/polarsource/polar/assets/281715/d0cd8a73-eb65-4eb8-a05b-f2264713febe">

### URL Namespaces

As part of this, we're cleaning up and setting namespaces for our URLs. Short-term, our `/pages` will contain redirects (~1 month) before being removed entirely to clean-up the codebase to this new structure.

**Maintainer**
- `/maintainer` - Maintainer onboarding
- `/maintainer/<github_org>/:page` - Maintainer view(s)
- `/maintainer/<github_org>/:page?repo=<repo>` – Maintainer view(s) w. local repository filter, e.g issues.

**Backer**
_Will reside across pages on the root_

- `/:page` – Backer view(s)
- `/feed` - Our first page. Just containing the issues they have backed + add for backing and their status.

**Organizations**
_Future: Support organization backers. Individuals will be backing, but this view will be to admin the organisation_
- `/org/[namespace]`

### Todo

- [ ] Move URLs (see below) in standalone PR
- [ ] Move `RepoSelection` into issues filter view
- [ ] Decouple org picker (backer vs. maintainer) and move into topbar to the right
- [ ] Implement backer view design

### URL Changes

- [x] Move `/issues` to `/maintainer/[organization]/issues`
- [x] Move `/finance` to `/maintainer/[organization]/finance`
- [x] Move `/promote` to `/maintainer/[organization]/promote`
- [x] Move `/dashboard/initialize/[organization]` to `/maintainer/[organization]/initialize`. 
    **Important:** Ensure redirect works with GitHub App installations etc before swapping those.
- [x] Move `/dependencies/personal` to `/feed`
- [x] Remove `/dependencies` (FED only at this stage). Killing a darling. Might resurface later, but differently and explicitly within the backer mode.
- [x] Move `/dashboard/settings` for the Chrome Extension
- [ ] Search backend for any links, e.g emails etc, to old URLs and update them

**Issues**
- `/issues` -> `/maintainer/[org]/issues` OR `/feed` (backer)
- `/issues/[organization]` -> `/maintainer/[organization]/issues`
- `/issues/[organization]/[repo]` -> `/maintainer/[organization]/issues?repo=[repo]`

**Finance**
- `/finance` -> `/maintainer` (Used to link to `/issues`)
- `/finance/[organization]` -> `/maintainer/[organization]/finance`
- `/finance/[organization]/rewarded` -> `/maintainer/[organization/finance/rewarded`

**TBD**: Instead of sub-pages under `/finance/[organization]/*` should we instead have URL query params of `tab` for the different tabs?

**Promote**
- `/promote` -> `/maintainer` (Used to link to `/issues`)
- `/promote/issues` -> `/maintainer` (Used to link to `/issues`)
- `/promote/issues/[organization]` -> `/maintainer/[organization]/promote/issues`
- `/promote/embeds` -> `/maintainer` (Used to link to `/issues`)
- `/promote/embeds/[organization]` -> `/maintainer/[organization]/promote/embeds`

**Feed**
- `/dependencies/personal` -> `/feed`

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/927">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/927/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/927/pledge.svg">
</picture>
</a>
